name: Artifactory build upon a push

on:
  release:
    types: [published]
  pull_request:
    types: [opened]
    branches:
      - '!release-branch'
      - release-1*
      - 1.*
      - develop
      - MOSIP*
  push:
    branches:
      - develop
      - 1.1.5
      - MOSIP-17721
      - release*
  
jobs:
  build-docker-artifactory-server:
    strategy:
      matrix:
        include:
          - SERVICE_LOCATION: 'artifacts'
            SERVICE_NAME: 'artifactory-server'
      fail-fast: false
    name: ${{ matrix.SERVICE_NAME }}
    uses: mosip/kattu/.github/workflows/docker-build.yml@master
    with:
      SERVICE_LOCATION: ${{ matrix.SERVICE_LOCATION }}
      SERVICE_NAME: ${{ matrix.SERVICE_NAME }}
    secrets:
      DEV_NAMESPACE_DOCKER_HUB: ${{ secrets.DEV_NAMESPACE_DOCKER_HUB }}
      ACTOR_DOCKER_HUB: ${{ secrets.ACTOR_DOCKER_HUB }}
      RELEASE_DOCKER_HUB: ${{ secrets.RELEASE_DOCKER_HUB }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
