name: Artifactory build upon a push

on:
  release:
    types: [published]
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:
    inputs:
      message:
        description: 'Message for manually triggering'
        required: false
        default: 'Triggered for Updates'
        type: string
  push:
    branches:
      - master
      - develop
      - 1.*
      - MOSIP*
      - release*
  
jobs:
  build-docker-artifactory-server:
    strategy:
      matrix:
        include:
          - SERVICE_LOCATION: 'artifacts'
            SERVICE_NAME: 'artifactory-server'
            SQUASH_LAYERS: '77'
            PLATFORMS: "linux/amd64"
      fail-fast: false
    name: ${{ matrix.SERVICE_NAME }}
    uses: mosip/kattu/.github/workflows/docker-build.yml@master
    with:
      SERVICE_LOCATION: ${{ matrix.SERVICE_LOCATION }}
      SERVICE_NAME: ${{ matrix.SERVICE_NAME }}
      SQUASH_LAYERS: ${{ matrix.SQUASH_LAYERS }}
      PLATFORMS: ${{ matrix.PLATFORMS }}
    secrets:
      DEV_NAMESPACE_DOCKER_HUB: ${{ secrets.DEV_NAMESPACE_DOCKER_HUB }}
      ACTOR_DOCKER_HUB: ${{ secrets.ACTOR_DOCKER_HUB }}
      RELEASE_DOCKER_HUB: ${{ secrets.RELEASE_DOCKER_HUB }}
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
